---
version: "2.1"
services:
  yarp:
    image: maplelolita/reverse-proxy:latest
    container_name: yarp
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    volumes:
      - /data/yarp/https:/https
    network_mode: host
    restart: always