---
version: "2.1"
services:
  yarp:
    image: maplelolita/reverse-proxy:latest
    container_name: yarp
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_Kestrel__Certificates__Default__Path= "/https/full.pem"
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath= "/https/key.pem"
    volumes:
      - /data/yarp/https:/https
    network_mode: host
    restart: always